site_name: 'Leitfaden CiviCRM Systopia'
site_url: https://systopia.de
repo_url: https://github.com/pbatroff/systopia_leitfaden
site_description: 'Leitfaden CiviCRM'
site_author: 'SYSTOPIA'
theme: material
markdown_extensions:
  - attr_list
  - admonition
  - def_list
  - codehilite(guess_lang=false)
  - toc(permalink=true)
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - pymdownx.tilde
  - pymdownx.betterem
  - pymdownx.mark

pages:
- Home: 'index.md'
- Einführung: '1. Einfuehrung/einfuehrung.md'
- CiviCRM installieren und konfigurieren - Technische Grundlagen:
    - 'Installation': '2. CiviCRM installieren und konfigurieren - technische grundlagen/2.1_installation.md'
    - 'Grundkonfiguration': '2. CiviCRM installieren und konfigurieren - technische grundlagen/2.2_grundkonfiguration.md'
    - 'CiviCRM und CMS - Integrationsmöglichkeiten in Ihre Website': '2. CiviCRM installieren und konfigurieren - technische grundlagen/2.3_civicrm_cms_integration.md'
- Kontakte und Beziehungen mit CiviCRM managen:
    - 'Kontakte und Beziehungen mit CiviCRM managen': '3. Kontakte und beziehungen mit civicrm managen/3_manage_contacts_relationships.md'
    - 'Kontaktarten': '3. Kontakte und beziehungen mit civicrm managen/3.1_contact_types.md'
    - 'Kontakte anlegen': '3. Kontakte und beziehungen mit civicrm managen/3.2_create_contacts.md'
    - 'Kontakte finden und bearbeiten': '3. Kontakte und beziehungen mit civicrm managen/3.3_find_edit_contacts.md'
    - 'Kontakte gruppieren und segmentieren': '3. Kontakte und beziehungen mit civicrm managen/3.4_group_contacts.md'
    - 'Kontakte exportieren': '3. Kontakte und beziehungen mit civicrm managen/3.5_export_contacts.md'
    - 'Kontakte importieren': '3. Kontakte und beziehungen mit civicrm managen/3.6_contact_import.md'
    - 'Beziehungen anlegen': '3. Kontakte und beziehungen mit civicrm managen/3.7_create_relationships.md'
    - 'Benutzerdefinierte Felder anlegen': '3. Kontakte und beziehungen mit civicrm managen/3.8_create_custom_fields.md'
- Kommunikation und Interaktion:
    - 'Eine begrenzte Anzahl E-Mail oder Briefe verschicken': '4. kommunikation und interaktion/4.1_send_letters_emails.md'
    - 'Vordefinition': '4. kommunikation und interaktion/4.2_defining_templates.md'
    - 'Massenmails und Newsletter': '4. kommunikation und interaktion/4.3_massmailings_newsletter.md'
    - 'Kontaktehistorie': '4. kommunikation und interaktion/4.4_contact_history.md'
- Daten Struktur: 'data_structure/data_structure.md'
