site_name: 'CiviCRM User Guide'
site_url: https://docs.civicrm.org/user/en/stable/
repo_url: https://github.com/civicrm/civicrm-user-guide
site_description: 'A guide for CiviCRM users.'
site_author: 'The CiviCRM community'
theme: material
markdown_extensions:
  - attr_list
  - admonition
  - def_list
  - codehilite(guess_lang=false)
  - toc(permalink=true)
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - pymdownx.tilde
  - pymdownx.betterem
  - pymdownx.mark

pages:
- Home: 'index.md'
- Einführung: '1. Einfuehrung/einfuehrung.md'
- CiviCRM installieren und konfigurieren - Technische Grundlagen:
    - 'Installation': '2. CiviCRM installieren und konfigurieren - technische grundlagen/2.1. installation.md'
    - 'Grundkonfiguration': '2. CiviCRM installieren und konfigurieren - technische grundlagen/2.2. grundkonfiguration.md'
    - 'CiviCRM und CMS - Integrationsmöglichkeiten in Ihre Website': '2. CiviCRM installieren und konfigurieren - technische grundlagen/2.3. civicrm und cms - integrationsmöglichkeiten in ihre website.md'
- Kontakte und Beziehungen mit CiviCRM managen:
    - 'Kontakte und Beziehungen mit CiviCRM managen': '3. Kontakte und beziehungen mit civicrm managen/3. kontakte und beziehungen mit civicrm managen.md'
    - 'Kontaktarten': '3. Kontakte und beziehungen mit civicrm managen/3.1. kontaktarten.md'
    - 'Kontakte anlegen': '3. Kontakte und beziehungen mit civicrm managen/3.2. kontakte anlegen.md'
    - 'Kontakte finden und bearbeiten': '3. Kontakte und beziehungen mit civicrm managen/3.3. kontakte finden und bearbeiten.md'
    - 'Kontakte gruppieren und segmentieren': '3. Kontakte und beziehungen mit civicrm managen/3.4. kontakte gruppieren und segmentieren.md'
    - 'Kontakte exportieren': '3. Kontakte und beziehungen mit civicrm managen/3.5. kontakte exportieren.md'
    - 'Kontakte importieren': '3. Kontakte und beziehungen mit civicrm managen/3.6. kontakte importieren.md'
    - 'Beziehungen anlegen': '3. Kontakte und beziehungen mit civicrm managen/3.7. beziehungen anlegen.md'
    - 'Benutzerdefinierte Felder anlegen': '3. Kontakte und beziehungen mit civicrm managen/3.8. benutzerdefinierte felder anlegen.md'
- Kommunikation und Interaktion:
    - 'Eine begrenzte Anzahl E-Mail oder Briefe verschicken': '4. kommunikation und interaktion/1. eine begrenzte anzahl e-mail oder briefe verschicken.md'
    - 'Vordefinition': '4. kommunikation und interaktion/2. vordefinition von vorlagen.md'
    - 'Massenmails und Newsletter': '4. kommunikation und interaktion/3. massenmails und newsletter.md'
    - 'Kontaktehistorie': '4. kommunikation und interaktion/4. kontakthistorie.md'
- Daten Struktur: 'X. Daten Struktur/X. Daten Struktur.md'
